repos:
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.9
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    # Ruff version.
    rev: "v0.0.269"
    hooks:
      - id: ruff
  - repo: github.com/pre-commit/pre-commit-hooks
    rev: "v4.4.0"
    hooks:
      - id: check-ast
      - id: check-byte-order-marker
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: pretty-format-json
      - id: check-symlinks
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: detect-aws-credentials
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
